// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/grpc.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetByUserRequest struct {
	Usrid                string   `protobuf:"bytes,1,opt,name=usrid,proto3" json:"usrid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUserRequest) Reset()         { *m = GetByUserRequest{} }
func (m *GetByUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetByUserRequest) ProtoMessage()    {}
func (*GetByUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{0}
}

func (m *GetByUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserRequest.Unmarshal(m, b)
}
func (m *GetByUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserRequest.Marshal(b, m, deterministic)
}
func (m *GetByUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserRequest.Merge(m, src)
}
func (m *GetByUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetByUserRequest.Size(m)
}
func (m *GetByUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserRequest proto.InternalMessageInfo

func (m *GetByUserRequest) GetUsrid() string {
	if m != nil {
		return m.Usrid
	}
	return ""
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type GetResponse struct {
	Logs                 []*Log   `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type PostRequest struct {
	Log                  *NewLog  `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{3}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetLog() *NewLog {
	if m != nil {
		return m.Log
	}
	return nil
}

type PostResponse struct {
	Log                  *NewLog  `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{4}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetLog() *NewLog {
	if m != nil {
		return m.Log
	}
	return nil
}

type PutRequest struct {
	LogId                int32    `protobuf:"varint,1,opt,name=logId,proto3" json:"logId,omitempty"`
	Log                  *Log     `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{5}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetLogId() int32 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *PutRequest) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type PutResponse struct {
	Log                  *Log     `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{6}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type NewLog struct {
	Id                        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message                   string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NotificationEmail         string   `protobuf:"bytes,3,opt,name=notification_email,json=notificationEmail,proto3" json:"notification_email,omitempty"`
	NotificationEmailOptional string   `protobuf:"bytes,4,opt,name=notification_email_optional,json=notificationEmailOptional,proto3" json:"notification_email_optional,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *NewLog) Reset()         { *m = NewLog{} }
func (m *NewLog) String() string { return proto.CompactTextString(m) }
func (*NewLog) ProtoMessage()    {}
func (*NewLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{7}
}

func (m *NewLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewLog.Unmarshal(m, b)
}
func (m *NewLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewLog.Marshal(b, m, deterministic)
}
func (m *NewLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewLog.Merge(m, src)
}
func (m *NewLog) XXX_Size() int {
	return xxx_messageInfo_NewLog.Size(m)
}
func (m *NewLog) XXX_DiscardUnknown() {
	xxx_messageInfo_NewLog.DiscardUnknown(m)
}

var xxx_messageInfo_NewLog proto.InternalMessageInfo

func (m *NewLog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NewLog) GetNotificationEmail() string {
	if m != nil {
		return m.NotificationEmail
	}
	return ""
}

func (m *NewLog) GetNotificationEmailOptional() string {
	if m != nil {
		return m.NotificationEmailOptional
	}
	return ""
}

type Log struct {
	Id                        int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Usrid                     string   `protobuf:"bytes,2,opt,name=usrid,proto3" json:"usrid,omitempty"`
	Message                   string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp                 int32    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UniquePhrase              string   `protobuf:"bytes,5,opt,name=unique_phrase,json=uniquePhrase,proto3" json:"unique_phrase,omitempty"`
	NotificationEmail         string   `protobuf:"bytes,6,opt,name=notification_email,json=notificationEmail,proto3" json:"notification_email,omitempty"`
	NotificationEmailOptional string   `protobuf:"bytes,7,opt,name=notification_email_optional,json=notificationEmailOptional,proto3" json:"notification_email_optional,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{8}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Log) GetUsrid() string {
	if m != nil {
		return m.Usrid
	}
	return ""
}

func (m *Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Log) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Log) GetUniquePhrase() string {
	if m != nil {
		return m.UniquePhrase
	}
	return ""
}

func (m *Log) GetNotificationEmail() string {
	if m != nil {
		return m.NotificationEmail
	}
	return ""
}

func (m *Log) GetNotificationEmailOptional() string {
	if m != nil {
		return m.NotificationEmailOptional
	}
	return ""
}

func init() {
	proto.RegisterType((*GetByUserRequest)(nil), "grpc.GetByUserRequest")
	proto.RegisterType((*GetRequest)(nil), "grpc.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "grpc.GetResponse")
	proto.RegisterType((*PostRequest)(nil), "grpc.PostRequest")
	proto.RegisterType((*PostResponse)(nil), "grpc.PostResponse")
	proto.RegisterType((*PutRequest)(nil), "grpc.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "grpc.PutResponse")
	proto.RegisterType((*NewLog)(nil), "grpc.NewLog")
	proto.RegisterType((*Log)(nil), "grpc.Log")
}

func init() { proto.RegisterFile("grpc/grpc.proto", fileDescriptor_81ea47a3f88c2082) }

var fileDescriptor_81ea47a3f88c2082 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xd1, 0x8a, 0xd3, 0x4c,
	0x14, 0xa6, 0x69, 0xd3, 0x92, 0x93, 0xf4, 0xdf, 0xdd, 0xc3, 0xfe, 0x12, 0xd3, 0x55, 0x96, 0x78,
	0x53, 0xc4, 0x6d, 0xa0, 0xde, 0x09, 0x2a, 0x88, 0x52, 0x84, 0xa2, 0x35, 0xb0, 0xd7, 0x25, 0x6e,
	0xc7, 0x31, 0x90, 0x66, 0xb2, 0x99, 0x09, 0x22, 0xb2, 0x37, 0xbe, 0x82, 0x4f, 0xe0, 0x0b, 0xf8,
	0x32, 0xbe, 0x82, 0xef, 0xe0, 0xad, 0xcc, 0x99, 0xb4, 0x9d, 0xba, 0xca, 0x82, 0x37, 0xa5, 0xe7,
	0xcc, 0xf7, 0x7d, 0xe7, 0x9b, 0x39, 0xe7, 0x04, 0x0e, 0x78, 0x5d, 0x5d, 0x24, 0xfa, 0x67, 0x52,
	0xd5, 0x42, 0x09, 0xec, 0xe9, 0xff, 0xd1, 0x09, 0x17, 0x82, 0x17, 0x2c, 0xc9, 0xaa, 0x3c, 0xc9,
	0xca, 0x52, 0xa8, 0x4c, 0xe5, 0xa2, 0x94, 0x06, 0x13, 0x8f, 0xe1, 0x70, 0xc6, 0xd4, 0xb3, 0x8f,
	0xe7, 0x92, 0xd5, 0x29, 0xbb, 0x6c, 0x98, 0x54, 0x78, 0x0c, 0x6e, 0x23, 0xeb, 0x7c, 0x15, 0x76,
	0x4e, 0x3b, 0x63, 0x2f, 0x35, 0x41, 0x1c, 0x00, 0xcc, 0x98, 0x6a, 0x31, 0xf1, 0x03, 0xf0, 0x29,
	0x92, 0x95, 0x28, 0x25, 0xc3, 0x3b, 0xd0, 0x2b, 0x04, 0x97, 0x61, 0xe7, 0xb4, 0x3b, 0xf6, 0xa7,
	0xde, 0x84, 0x5c, 0xcc, 0x05, 0x4f, 0x29, 0x1d, 0x9f, 0x81, 0xbf, 0x10, 0x72, 0x43, 0xc6, 0xbb,
	0xd0, 0x2d, 0x04, 0x27, 0x79, 0x7f, 0x1a, 0x18, 0xf0, 0x2b, 0xf6, 0x41, 0xe3, 0xf5, 0x41, 0x3c,
	0x81, 0xc0, 0xc0, 0x5b, 0xf5, 0x9b, 0xf0, 0x4f, 0x01, 0x16, 0x8d, 0xb2, 0xec, 0x17, 0x82, 0xbf,
	0x34, 0xf6, 0xdd, 0xd4, 0x04, 0x38, 0x32, 0x1a, 0x0e, 0x69, 0x58, 0x06, 0x49, 0xe0, 0x3e, 0xf8,
	0x24, 0xd0, 0xd6, 0x1b, 0xd9, 0xf5, 0x7e, 0xc7, 0x7e, 0xed, 0x40, 0xdf, 0x14, 0xc7, 0xff, 0xc0,
	0xd9, 0xbe, 0x92, 0x93, 0xaf, 0x30, 0x84, 0xc1, 0x9a, 0x49, 0x99, 0x71, 0x46, 0x75, 0xbc, 0x74,
	0x13, 0xe2, 0x19, 0x60, 0x29, 0x54, 0xfe, 0x2e, 0xbf, 0xa0, 0xd7, 0x5f, 0xb2, 0x75, 0x96, 0x17,
	0x61, 0x97, 0x40, 0x47, 0xf6, 0xc9, 0x0b, 0x7d, 0x80, 0x4f, 0x60, 0x74, 0x1d, 0xbe, 0x14, 0x95,
	0x0e, 0xb2, 0x22, 0xec, 0x11, 0xef, 0xf6, 0x35, 0xde, 0xeb, 0x16, 0x10, 0xff, 0xec, 0x40, 0x77,
	0xdf, 0xa0, 0x4b, 0x06, 0xb7, 0x9d, 0x75, 0xac, 0xce, 0xda, 0xb6, 0xbb, 0xfb, 0xb6, 0x4f, 0xc0,
	0x53, 0xf9, 0x9a, 0x49, 0x95, 0xad, 0x2b, 0xaa, 0xea, 0xa6, 0xbb, 0x04, 0xde, 0x83, 0x61, 0x53,
	0xe6, 0x97, 0x0d, 0x5b, 0x56, 0xef, 0xeb, 0x4c, 0xb2, 0xd0, 0x25, 0x76, 0x60, 0x92, 0x0b, 0xca,
	0xfd, 0xe5, 0xe6, 0xfd, 0x7f, 0xbc, 0xf9, 0xe0, 0x86, 0x9b, 0x4f, 0xbf, 0x39, 0xd0, 0x9f, 0x0b,
	0xce, 0x59, 0x8d, 0x8f, 0x61, 0x30, 0x63, 0x6a, 0x2e, 0xb8, 0xc4, 0x43, 0xd3, 0xc3, 0xdd, 0xfc,
	0x46, 0x47, 0x56, 0xc6, 0x74, 0x3d, 0x1e, 0x7e, 0xfe, 0xfe, 0xe3, 0x8b, 0x33, 0x40, 0x37, 0xd1,
	0x33, 0x8b, 0x6f, 0x60, 0xd8, 0xd2, 0xcd, 0x76, 0xe0, 0xad, 0x2d, 0x65, 0x6f, 0x5d, 0xfe, 0x24,
	0xf5, 0x3f, 0x49, 0x1d, 0xe0, 0x90, 0xa4, 0x92, 0x4f, 0xf4, 0xce, 0x57, 0xf8, 0x1c, 0x06, 0x7a,
	0xae, 0x75, 0x67, 0x5a, 0x92, 0xb5, 0x15, 0x11, 0xda, 0xa9, 0x56, 0x08, 0x49, 0x28, 0x88, 0x8d,
	0xa7, 0x47, 0x7a, 0x00, 0x71, 0x0e, 0xde, 0x79, 0xb5, 0xca, 0x14, 0xd3, 0x3a, 0xed, 0xcd, 0x76,
	0xe3, 0xbf, 0xb1, 0x63, 0xcd, 0x73, 0x1c, 0x91, 0xca, 0x71, 0xb4, 0xb1, 0x43, 0x1b, 0x71, 0x45,
	0x6a, 0x6f, 0xfb, 0xf4, 0x1d, 0x78, 0xf8, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x62, 0xfc, 0xa1,
	0x3e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	GetLogs(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetLogsByUser(ctx context.Context, in *GetByUserRequest, opts ...grpc.CallOption) (*GetResponse, error)
	PostLog(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	UpdateLog(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) GetLogs(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/grpc.Logger/GetLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) GetLogsByUser(ctx context.Context, in *GetByUserRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/grpc.Logger/GetLogsByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) PostLog(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/grpc.Logger/PostLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) UpdateLog(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/grpc.Logger/UpdateLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	GetLogs(context.Context, *GetRequest) (*GetResponse, error)
	GetLogsByUser(context.Context, *GetByUserRequest) (*GetResponse, error)
	PostLog(context.Context, *PostRequest) (*PostResponse, error)
	UpdateLog(context.Context, *PutRequest) (*PutResponse, error)
}

// UnimplementedLoggerServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (*UnimplementedLoggerServer) GetLogs(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (*UnimplementedLoggerServer) GetLogsByUser(ctx context.Context, req *GetByUserRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogsByUser not implemented")
}
func (*UnimplementedLoggerServer) PostLog(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostLog not implemented")
}
func (*UnimplementedLoggerServer) UpdateLog(ctx context.Context, req *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLog not implemented")
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Logger/GetLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).GetLogs(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_GetLogsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).GetLogsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Logger/GetLogsByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).GetLogsByUser(ctx, req.(*GetByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_PostLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).PostLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Logger/PostLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).PostLog(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_UpdateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).UpdateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Logger/UpdateLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).UpdateLog(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogs",
			Handler:    _Logger_GetLogs_Handler,
		},
		{
			MethodName: "GetLogsByUser",
			Handler:    _Logger_GetLogsByUser_Handler,
		},
		{
			MethodName: "PostLog",
			Handler:    _Logger_PostLog_Handler,
		},
		{
			MethodName: "UpdateLog",
			Handler:    _Logger_UpdateLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/grpc.proto",
}
